### ISSUE TITLE
File paths are not properly converted for TeX syntax

### ISSUE THREAD

**Issue by raineszm** [raineszm/obsidian-export-to-tex#20]
There is an issue with absolute path and Windows:

Windows paths are by default (?) defined with `\` backslashes, which is not recognized by `\includegraphics`. Changing `\`s to `/` would fix it.

Thanks.

_Originally posted by @psyguy in https://github.com/raineszm/obsidian-export-to-tex/issues/17#issuecomment-776730354_

**Comment by raineszm** [comment]
I think this is fixed in the most recent commit, but I don't have a windows machine to test on. Could you try out the plugin in this vault (plugin version should read 0.1.1-0) and let me know if it works on your machine? If so I'll push an update [Minimal Working Vault.zip](https://github.com/raineszm/obsidian-export-to-tex/files/5961301/Minimal.Working.Vault.zip)

**Comment by psyguy** [comment]
The new version cannot be installed via Obsidian due to a 404 error:

![image](https://user-images.githubusercontent.com/8527082/107614322-60a8ff80-6c4a-11eb-8fd5-2d334aaeb600.png)

**Comment by raineszm** [comment]
Interesting. It should have already been present in the vault. In a little bit I'll just publish the new version since it shouldn't break anything.

**Comment by raineszm** [comment]
Okay. I pushed version 0.1.1 with the changes. Let me know how that works for you. I'll reopen the issue until we can confirm that things are working.

**Comment by psyguy** [comment]
Hi again,

Thanks for implementing issue #18. Though, the new version gives the wrong paths.

- For **Absolute path**: `\includegraphics{\\?\C:\path\to\vault-root\Attachments\Figures\Pasted image 20210124190412.png}`
  - Still backslashes `\` instead of `/`
  - Redundant `\\?`
- For **Relative to export directory**: `\includegraphics{{..\Attachments\Figures\Pasted image 20210124191222}.png}`
  - Still backslashes `\` instead of `/`
  - Redundant `{` and `}`

- **Relative to vault root** works properly: `\includegraphics{Attachments/Figures/Pasted image 20210124191222.png}` ✅

**Comment by raineszm** [comment]
Thanks. Needs more work I see.

**Comment by raineszm** [comment]
This should hopefully be working now in version 0.2.0. I tested it locally running Obsidian in wine, but let me know if there are still issues.

**Comment by psyguy** [comment]
Thanks for the quick fix!

The only issue is with the option **Relative to export directory**, which still prints `\` instead of `/`.

**Comment by raineszm** [comment]
> Thanks for the quick fix!
> 
> The only issue is with the option **Relative to export directory**, which still prints `\` instead of `/`.

Should (hopefully!) be fixed in 0.2.1.

**Comment by psyguy** [comment]
Thanks, it's fixed! 😌
